/// Flutter icons DrBotIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DrBotIcons
///      fonts:
///       - asset: fonts/DrBotIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DrBotIcons {
  DrBotIcons._();

  static const _kFontFam = 'DrBotIcons';
  static const String? _kFontPkg = null;

  static const IconData group_127 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData path_3 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData path_421 = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_3 = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_25 = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_117 = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
